
						# Specify the template type. Valid values are as follows.
						# For Terraform: TF
						# For AWS CloudFormation: CFT
						# For Kubernetes: K8S

template_type: CFT

						# If template_type value is CFT, set cft_parameters (optional)
						# variable_values is an array of name/value pairs, which identifies the
						# template variables

cft_parameters:
variable_values:
- name:KeyName
value: 10
- name: AMI
value: ami-45785
										
